server {
    listen 80;
    server_name localhost;

    # Dynamic App (Aplikasi PHP)
    location / {
        root /var/www/html;
        index index.php index.html;
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Static App (CV) -> Pastikan alias / root-nya mengarah ke folder static yang benar
    location /static-cv/ {
        alias /var/www/static-cv/;
        index index.html;
        try_files $uri $uri/ =404;
    }

    # Konfigurasi PHP-FPM
    location ~ \.php$ {
        root /var/www/html;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}